### PR TITLE
add menu for file list split action.

### PR DESCRIPTION
**Pull request by roachsinai**
触发`Leaderf file`之后，按下`C-\`，会在下方弹出如何分割Leaderf选中的文件的选项。

### CODE REVIEW

**Comment by roachsinai** [comment]
image

**Comment by Yggdroot** [comment]
Great. However there seem to be a bug if select `Drop`, It works as if `<CR>` is pressed. Is it by design?

**Comment by Yggdroot** [comment]
Also could you add the explanation for `C-\` in readme?

**Comment by roachsinai** [comment]
Yeah, by design.

If there is a window of that file's buffer, switch to that window, or open it in current window.

**Comment by roachsinai** [comment]
@Yggdroot I'm checking one thing. Please wait for a while.

**Comment by roachsinai** [comment]
I think no question about this PR.

---

But found a bug for `C-X` and `C-]`, this PR is not involved!

Like we have two window, one for file `tt.c`, one for `tt.i`, then we trigger `Leaderf file` when focus `tt.c` then use `C-]` split `tt.i`.

What expected is there are two window for `tt.i`, on window for `tt.c`. But what got is two window for `tt.c`, on window for `tt.i`.

截图录屏_konsole_20200713151850

If need I can make a issue for this bug.

**Comment by cage1618** [comment]
使用 Leaderf rg 搜索然后打开文件的时候会报错：NvimError('Vim(drop):E479: No match')，导致文件打不开

**Comment by roachsinai** [comment]
vim没有错啊...

**Comment by Yggdroot** [comment]
> 
> 
> 使用 Leaderf rg 搜索然后打开文件的时候会报错：NvimError('Vim(drop):E479: No match')，导致文件打不开

怎么复现，我用nvim也没复现。

**Comment by cage1618** [comment]
目标文件在 wildignore 中就会触发
```
set wildignore+=*/.idea,*/.npm/*,*/.sass-cache/*,*/.vscode/*
set wildignore+=*/node_modules/*,*/.happypack/*,*/.hg/*,*/*.swp
set wildignore+=*/run/*,*/dist/*,*.pyc,*/.git/*,*/.svn/*,*/*.swo,*/bak/*
```
比如上面的配置中，我在 node_modules 目录下搜索的时候能搜出东西，但想打开那个文件就会报上名的错误

**Comment by cage1618** [comment]
尝试回退下了版本，发现也有这个问题，应该不是这个 pr 造成的

**Comment by xaljer** [comment]
Does this pr support other sub-commands?

**Comment by roachsinai** [comment]
If shortcuts like <C-T>, <C-]> supports, <C-\> supports, for example `Leaderf mur`.

In fact, it should support most sub-commands(didn't for all), for example `Leaderf function`, if you choose vsplit, it vsplit that file and focus the function you found.

**Pull request merged**
