### PR TITLE
Add options "g:Lf_AutoResize"

### PR DESCRIPTION
**Pull request by tamago324**
Added an option to resize automatically.
I was wondering whether to add an argument like `--auto-resize`. Is it necessary?

### CODE REVIEW

**Comment by tamago324** [comment]
Thank you for your comment.
Since I do not use neovim, I do not know how to implement a floating window, so I think it is difficult to respond.
Fixed behavior on Vim.

**Comment by Yggdroot** [comment]
What is this option used for?

**Comment by tamago324** [comment]
If the number of lines is smaller than the height of the window, such as `g:Lf_ReverseOrder`, the height of the window is automatically resized.

Options that exist in plugins like ctrlp and denite.

**Comment by Yggdroot** [comment]
Got it.

**Comment by tamago324** [comment]
Thank you!

**Pull request merged**
