### PR TITLE
Add <C-w> command to pyhton cli

### PR DESCRIPTION
**Pull request by Misfit-John**
I don't used to use <C-u> to clean whole line, I used to use <C-w> to clean a word, so i just add a choice for you to clear the input. Just a very little improve.

### CODE REVIEW

**Comment by Yggdroot** [comment]
The behavior of `<C-W>` is not consistent with that of vim. (`:h c_CTRL-W`).  Please merge the commits into one commit if there is only one feature, I want a clean commit history. 
I don't want to accept '[avoid showing searching if there is no content in mru](https://github.com/Yggdroot/LeaderF/pull/19/commits/4018df610a9afc73d1035a70ec5697510e064f47)'

**Comment by Misfit-John** [comment]
Ok, I get that, it depends on the 'iskeyword' setting, hmm, I am closing this pull request because you wanna keep it clean with user's setting and I don't wanna make the <c-w> that complicate, I will keep it locally.Do you really don't care about the 'searching....' message if the content is empty? It looks like a bug from my side.

**Comment by Yggdroot** [comment]
I did not mean `'iskeyword'`. If you try `<c-w>` a string like this `'aaa....bbb......ccc.....'`(where '.' means space), you'll know what I mean. i.e., if the cursor is at the end of the string, 'ccc' will be removed.

**Comment by Misfit-John** [comment]
I get that, so I close the pull request , I think it will be too complicate to simulate the whole <c-w> work in a python cli, so let forget it, it's not necessary after all.

**Pull request closed without merging**
