### PR TITLE
Make it possible to remap highlight groups from a user colorscheme

### LINKED ISSUE #402: Bad colors for default Gvim colorscheme (white)
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov 17 2019 23:02:10)
MS-Windows 64-bit GUI version with OLE support
Included patches: 1-2318
Compiled by appveyor@APPVYR-WIN
Huge version with GUI.  Features included (+) or not (-):
+acl                +comments           +file_in_path       +listcmds           +persistent_undo    -sun_workshop       +vertsplit
+arabic             +conceal            +find_in_path       +localmap           -postscript         +syntax             +virtualedit
+autocmd            +cryptv             +float              +lua/dyn            +printer            +tag_binary         +visual
+autochdir          +cscope             +folding            +menu               +profile            -tag_old_static     +visualextra
+autoservername     +cursorbind         -footer             +mksession          +python/dyn         -tag_any_white      +viminfo
+balloon_eval       +cursorshape        +gettext/dyn        +modify_fname       +python3/dyn        +tcl/dyn            +vreplace
-balloon_eval_term  +dialog_con_gui     -hangul_input       +mouse              +quickfix           -termguicolors      -vtp
+browse             +diff               +iconv/dyn          +mouseshape         +reltime            +terminal           +wildignore
++builtin_terms     +digraphs           +insert_expand      +multi_byte_ime/dyn +rightleft          -termresponse       +wildmenu
+byte_offset        +directx            +job                +multi_lang         +ruby/dyn           +textobjects        +windows
+channel            -dnd                +jumplist           +mzscheme/dyn       +scrollbind         +textprop           +writebackup
+cindent            -ebcdic             +keymap             +netbeans_intg      +signs              -tgetent            -xfontset
+clientserver       +emacs_tags         +lambda             +num64              +smartindent        +timers             -xim
+clipboard          +eval               +langmap            +ole                +sound              +title              +xpm_w32
+cmdline_compl      +ex_extra           +libcall            +packages           +spell              +toolbar            -xterm_save
+cmdline_hist       +extra_search       +linebreak          +path_extra         +startuptime        +user_commands      
+cmdline_info       -farsi              +lispindent         +perl/dyn           +statusline         +vartabs            
   system vimrc file: "$VIM\vimrc"
     user vimrc file: "$HOME\_vimrc"
 2nd user vimrc file: "$HOME\vimfiles\vimrc"
 3rd user vimrc file: "$VIM\_vimrc"
      user exrc file: "$HOME\_exrc"
  2nd user exrc file: "$VIM\_exrc"
  system gvimrc file: "$VIM\gvimrc"
    user gvimrc file: "$HOME\_gvimrc"
2nd user gvimrc file: "$HOME\vimfiles\gvimrc"
3rd user gvimrc file: "$VIM\_gvimrc"
       defaults file: "$VIMRUNTIME\defaults.vim"
    system menu file: "$VIMRUNTIME\menu.vim"
Compilation: cl -c /W3 /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32  -DFEAT_CSCOPE -DFEAT_TERMINAL -DFEAT_SOUND -DFEAT_NETBEANS_INTG -DFEAT_JOB_CHANNEL   -DFEAT_XPM_W32   -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 /MP -DHAVE_STDINT_H /Ox /GL -DNDEBUG  /Zl /MT -DFEAT_OLE -DFEAT_MBYTE_IME -DDYNAMIC_IME -DFEAT_GUI_MSWIN -DFEAT_DIRECTX -DDYNAMIC_DIRECTX -DFEAT_DIRECTX_COLOR_EMOJI -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_TCL -DDYNAMIC_TCL -DDYNAMIC_TCL_DLL=\"tcl86t.dll\" -DDYNAMIC_TCL_VER=\"8.6\" -DFEAT_LUA -DDYNAMIC_LUA -DDYNAMIC_LUA_DLL=\"lua53.dll\" -DFEAT_PYTHON -DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL=\"python37.dll\" -DFEAT_MZSCHEME -I "C:\Program Files\Racket\include" -DMZ_PRECISE_GC -DDYNAMIC_MZSCHEME -DDYNAMIC_MZSCH_DLL=\"libracket3m_a36fs8.dll\" -DDYNAMIC_MZGC_DLL=\"libracket3m_a36fs8.dll\" -DFEAT_PERL -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DDYNAMIC_PERL -DDYNAMIC_PERL_DLL=\"perl528.dll\" -DFEAT_RUBY -DDYNAMIC_RUBY -DDYNAMIC_RUBY_VER=24 -DDYNAMIC_RUBY_DLL=\"x64-msvcrt-ruby240.dll\" -DFEAT_HUGE /Fd.\ObjGXOULYHTRZAMD64/ /Zi
Linking: link  /nologo /opt:ref /LTCG:STATUS /HIGHENTROPYVA:NO oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib netapi32.lib uuid.lib /machine:AMD64 gdi32.lib version.lib   winspool.lib comctl32.lib advapi32.lib shell32.lib netapi32.lib  /machine:AMD64  libcmt.lib oleaut32.lib user32.lib  /nodefaultlib:lua53.lib  /STACK:8388608  /nodefaultlib:python27.lib /nodefaultlib:python37.lib   "C:\Tcl\lib\tclstub86.lib" winmm.lib WSock32.lib xpm\x64\lib-vc14\libXpm.lib /PDB:gvim.pdb -debug

```

- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): python27.dll
- Output of `:echo &pythonthreedll`(only vim, not neovim): python37.dll
- Output of `:py print(sys.version)`:
```
Error detected while processing function EvalVim:
line   31:
E370: Could not load library python27.dll
Error detected while processing function EvalVim:
line   31:
E263: Sorry, this command is disabled, the Python library could not be loaded.
``` 
- Output of `:py3 print(sys.version)`: `3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]` 
- Output of `:echo g:Lf_Debug_Cmd`: `rg --no-messages --files   -g "!.svn" -g "!.git" -g "!.hg" -g "!*.sw?" -g "!~$*" -g "!*.bak" -g "!*.exe" -g "!*.o" -g "!*.so" -g "!*.py[co]" -g "!*.tmp" -g "!*.ttf" -L --hidden` 
- Output of `:echo g:Lf_FilesFromCache`:  0
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```
	let g:Lf_WindowPosition = 'popup'
	let g:Lf_StlSeparator = { 'left': '', 'right': '' }
	let g:Lf_ShortcutF = '<leader>ff'
	let g:Lf_Shortcutb = '<leader>b'
	let g:Lf_WindowHeight = 0.30
	let g:Lf_ShowHidden = 1
	let g:Lf_FollowLinks = 1
	let g:Lf_NormalMap = {"File":   [["u", ':LeaderfFile ..<CR>']]}
    let g:Lf_PreviewResult = { 'BufTag': 0 }
    let g:Lf_WildIgnore = {
            \ 'dir': ['.svn','.git','.hg'],
            \ 'file': ['*.sw?','~$*','*.bak','*.exe','*.o','*.so','*.py[co]', '*.tmp','*.ttf']
            \}
    let g:Lf_MruWildIgnore = copy(g:Lf_WildIgnore)
	let g:Lf_UseVersionControlTool = 0
	nnoremap <leader>f/ :Leaderf rg 
	nnoremap <leader>/ :LeaderfLine<CR>
	nnoremap <leader>f; :LeaderfHistoryCmd<CR>
	nnoremap <leader>ftt :LeaderfTag<CR>
	nnoremap <leader>ftb :LeaderfBufTag<CR>
	nnoremap <leader>fh :LeaderfHelp<CR>
	nnoremap <leader>fm :LeaderfMru<CR>
	nnoremap <leader>fs :LeaderfSelf<CR>
	nnoremap <leader>fc :LeaderfColorscheme<CR>
	nnoremap <leader>fdd :LeaderfFile ~/docs<CR>
	packadd LeaderF
```

### Describe your question, feature request, or bug.
default colors are subjectively bad

### Steps to reproduce
Open GVim with default light colorscheme and run leaderf in popup

### Actual behaviour
image

image

If you manually `set background=dark` then it looks ok:
image

But the rest of vim syntax highlighting becomes unreadable.

### PR DESCRIPTION
**Pull request by habamax**
Use `hi def` where possible instead of `hi`.

Also partially fixes #402

### CODE REVIEW

**Comment by habamax** [comment]
image

**Comment by Yggdroot** [comment]
I have already do it in dev branch at https://github.com/Yggdroot/LeaderF/commit/9762be1efb8f938946dfa477e5eca877b1838f09.

**Comment by habamax** [comment]
> I have already do it in dev branch at [9762be1](https://github.com/Yggdroot/LeaderF/commit/9762be1efb8f938946dfa477e5eca877b1838f09).

Ohh, oops. I thought I could help you here :)

Thank you so much for that!

**Comment by Yggdroot** [comment]
dev branch has been merged.

**Comment by habamax** [comment]
Thank a lot! Looks like you simplified (reduced amount of highlight groups) it a bit, which is good!

I have updated my colorschemes accordingly.

**Pull request closed without merging**
