### PR TITLE
Temporary fix for vim/vim#3117

### PR DESCRIPTION
**Pull request by arthurkiller**
fix python 3.7 depreciate problem.

### CODE REVIEW

**Comment by arthurkiller** [comment]
@Yggdroot I have fixed #138 here.

**Comment by Yggdroot** [comment]
138 has already been fixed by https://github.com/Yggdroot/LeaderF/commit/f72300bca95d46635ba2623c01f1df911446b817.

**Comment by arthurkiller** [comment]
okay

**Comment by arthurkiller** [comment]
image
But in my pull, this warning disappeared

**Comment by Yggdroot** [comment]
This error is reported by YCM, because YCM is also written in Python. You can disable YCM and have a try.
The fix can only make sure that LeaderF won't report the message.

**Comment by arthurkiller** [comment]
Are you sure 
> +silent! exec g:Lf_py "pass"
can silent other python3 plugins?

**Comment by arthurkiller** [comment]
Ohhh, I get it. I was misleading. thx for your reply

**Comment by Yggdroot** [comment]
You can add 
```vim
if has('python3')
  silent! python3 1
endif
```
into vimrc to supress the error message for all plugin.

**Comment by arthurkiller** [comment]
Great idea, thx dude.

**Comment by Yggdroot** [comment]
NP, thanks for supporting LeaderF.

**Pull request closed without merging**
