### PR TITLE
Add command quickfix/loclist output ot `Leaderf line`

### PR DESCRIPTION
**Pull request by tamago324**
I tried to make it so that it can be output to quickfix and loclist in the `Leaderf line` as in #488.

If you think it's good, I'd be happy to merge them.

Thank you!

### CODE REVIEW

**Comment by Yggdroot** [comment]
I got an error when pressing Q or L in normal mode:

```
Traceback (most recent call last):
Error detected while processing function leaderf#Line#NormalModeFilter:
line   96:
  File "<string>", line 1, in <module>
Error detected while processing function leaderf#Line#NormalModeFilter:
line   96:
  File "C:\.vim\plugged\LeaderF\autoload\leaderf\python\leaderf\lineExpl.py", line 140, in outputToQflist
Error detected while processing function leaderf#Line#NormalModeFilter:
line   96:
    items = self._getFormatedContents()
Error detected while processing function leaderf#Line#NormalModeFilter:
line   96:
  File "C:\.vim\plugged\LeaderF\autoload\leaderf\python\leaderf\lineExpl.py", line 153, in _getFormatedContents
Error detected while processing function leaderf#Line#NormalModeFilter:
line   96:
    text, info = line.rsplit("\t", 1)
Error detected while processing function leaderf#Line#NormalModeFilter:
line   96:
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by tamago324** [comment]
Does it occur when there are zero results?

**Comment by Yggdroot** [comment]
Maybe it's caused by `let g:Lf_HideHelp = 0`.

**Comment by tamago324** [comment]
I'm going to modify it as follows.

```py
      def _getFormatedContents(self):
          items = []
          for line in self._instance._buffer_object:
+             if '\t' not in line:
+                 continue
              text, info = line.rsplit("\t", 1)
              info = info[1:-1]    # file:line buf_number
              line_nr, buf_number = info.rsplit(":", 1)[1].split()
              items.append({
                  "filename": lfEval("getbufinfo(%d)[0]['name']" % int(buf_number)),
                  "lnum": line_nr,
                  "col": 1,
                  "text": text,
              })
          return items

```

**Comment by Yggdroot** [comment]
```diff
diff --git a/autoload/leaderf/python/leaderf/lineExpl.py b/autoload/leaderf/python/leaderf/lineExpl.py
index 961411a..ceba19c 100644
--- a/autoload/leaderf/python/leaderf/lineExpl.py
+++ b/autoload/leaderf/python/leaderf/lineExpl.py
@@ -149,7 +149,7 @@ class LineExplManager(Manager):

     def _getFormatedContents(self):
         items = []
-        for line in self._instance._buffer_object:
+        for line in self._instance._buffer_object[self._help_length:]:
             text, info = line.rsplit("\t", 1)
             info = info[1:-1]    # file:line buf_number
             line_nr, buf_number = info.rsplit(":", 1)[1].split()
```
would be OK.

**Comment by tamago324** [comment]
It looks very good.

**Comment by tamago324** [comment]
Fixed.

**Comment by tamago324** [comment]
Thank you for merging!

**Pull request merged**
