### PR TITLE
LeaderfTag should also take consider of Lf_JumpToExistingWindow

### PR DESCRIPTION
**Pull request by hao-lee**
Actually, this is the real solution for #643.

Signed-off-by: Hao Lee <haolee.swjtu@gmail.com>

### CODE REVIEW

**Comment by planykao** [comment]
[https://github.com/Yggdroot/LeaderF/commit/f25fd1729b0dc80ed960d6e0025210e30e855d8f](url)

Open gtags search result in new tab is broken in this commit, lfCmd takes 2 variables.

`--- a/autoload/leaderf/python/leaderf/gtagsExpl.py
+++ b/autoload/leaderf/python/leaderf/gtagsExpl.py
@@ -911,9 +911,9 @@ class GtagsExplManager(Manager):
         try:
             if kwargs.get("mode", '') == 't':
                 if lfEval("get(g:, 'Lf_JumpToExistingWindow', 1)") == '1':
-                    lfCmd("tab drop %s" % (escSpecial(file), line_num))
+                    lfCmd("tab drop %s | %s" % (escSpecial(file), line_num))
                 else:
-                    lfCmd("tabe %s" % (escSpecial(file), line_num))
+                    lfCmd("tabe %s | %s" % (escSpecial(file), line_num))`

**Comment by leisiji** [comment]
I also found this problem, @Yggdroot

**Comment by Yggdroot** [comment]
@leisiji  What's the problem?

**Comment by Yggdroot** [comment]
@leisiji  Got it.

**Comment by Yggdroot** [comment]
@planykao @leisiji  fixed.

**Comment by hao-lee** [comment]
@Yggdroot Thanks, Sorry for that inconvenience @PetrusZ @leisiji

**Pull request merged**
